### ISSUE TITLE
jmap-mua: Automatic mailbox creation fails if mailbox of the same name already exists

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/jmap#32]
Some methods like `moveToTrash` or `archive` will automatically create mailboxes with their respective roles. However if a mailbox with the same name (but different role) already exists the call will fail.

We need to handle that somehow (pick a different name? modify the existing mailbox? just use the mailbox?)

**Comment by cketti** [comment]
Automatically creating folders has caused a lot of support issues for K-9 Mail. My advice is to not do it. Instead, make it part of the setup flow. If a particular special role mailbox doesn't exist, offer users an easy way to create it. 

Related: Many users intentionally don't use certain special mailboxes. I can understand if you'd like to keep the number of optional features small. But I'm sure users would appreciate the options of not using an Archive or Trash mailbox.

**Comment by iNPUTmice** [comment]
> We need to handle that somehow (pick a different name? modify the existing mailbox? just use the mailbox?)

90% of users will probably want to change the role to match the name. I can’t think of a lot of reasons for having a mailbox name 'Archive', or 'Trash' that doesn’t have a role of the same name.
Ltt.rs should just prompt the user asking them to confirm the role change (from none to x) with a full screen window explaining the change with pictograms and stuff.
Users who want to do something different will almost certainly have a different (IMAP) client installed somewhere and be able to perform some other changes that ultimately lead to the creation of a mailbox with a proper role that jmap-mua can use.

@cketti Ltt.rs is essentially an experiment in how easy we can make an email client while covering 80% of users. There are plenty of more advanced email clients both in general and also on Android. I’m OK with the experiment failing. But giving up before Ltt.rs even has users is not the right way.
The functionality of jmap-client will not be impacted by any of those decisions at all.
