### ISSUE TITLE
RFC 8887: A JMAP Subprotocol for WebSocket

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/jmap#42]
* [ ] Any place current de serializing to GenericResponse should de serialize to `GenericWebSocketMessage`. This deserializer will look at `@type` to decide whether to invoke `ErrorResponse`, `Response`, or `PushMessage` on the payload. `GenericWebSocketMessage` will consist of a `String id` and a `Object payload` in form of ErrorResponse or Response. This GenericWebSocketMessage will have typed subclasses so we can run instance of on it.

**Comment by chibenwa** [comment]
Just to make it clear: James right now supports both webSocket and event source (a kind contributor wrote the event source during his vacations ;-) )

**Comment by iNPUTmice** [comment]
Yes I saw that. Thank you. EventSource will definitely be implemented first. But once I've setup James (and have access to a server that supports WebSocket) it’s probably a good idea to think about how to implement that as well.

**Comment by iNPUTmice** [comment]
This has been implemented in 0.6.1
