### ISSUE TITLE
jmap-mock-server: Implement websocket support

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/jmap#54]
This should also give us a convenient way to implement push support into the mock server without having to deal with EventSource.

**Comment by chibenwa** [comment]
I am just curious: what are the reasons that might make one maybe not want to deal with event source?

**Comment by iNPUTmice** [comment]
> I am just curious: what are the reasons that might make one maybe not want to deal with event source?

That’s just a particular problem of the HTTP Mock server implementation I’m using. It has native support for WebSockets but nothing for EventSource. Anything that actually waits for pushes would have to be coded manually.

As far as JMAP as a whole is concerned EventSource is actually fine. On the contrary I haven’t really seen the upside of WebSockets yet.

**Comment by iNPUTmice** [comment]
Fixed in 37a23f766bc988dc18654ef12561b249ceabbaeb and a06308fbad53d77ec69bfbd9cd19b7512eb76857
