### ISSUE TITLE
Failure when execute query mail using Mua

### ISSUE THREAD

**Issue by thoangtd** [iNPUTmice/jmap#77]
`   // Query mail
            EmailQuery emailQuery = EmailQuery.unfiltered();
            mua.query(emailQuery, false).get();
            Collection<String> emailIds = cache.getEmailIds();`

java.util.concurrent.ExecutionException: rs.ltt.jmap.client.api.MethodErrorResponseException: invalidArguments in response to Email/get (The following properties [header:Autocrypt:asText:all] do not exist.)
pls help me how to fix this problem, thanks

**Comment by iNPUTmice** [comment]
What JMAP server are you trying this with? Those headers are custom header requests but in general every JMAP server should support them.

**Comment by thoangtd** [comment]
I am using lib to connect to the James mail server, and in James's configuration, I can't find the configuration for the those headers

**Comment by iNPUTmice** [comment]
See https://www.rfc-editor.org/rfc/rfc8621#section-4.1.3

**Comment by chibenwa** [comment]
Likely a james bug, please report on James project bug tracker

**Comment by thoangtd** [comment]
Thanks @chibenwa for support,
 I need to support pagination when user query email with filter, look like 
[
<img width="935" alt="image" src="https://user-images.githubusercontent.com/2314216/217996349-1e35c945-33c4-4124-8882-488583e01a70.png">
](url)
